# Generated by Django 4.2.3 on 2023-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_quantity_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Medicinal'), ('R', 'Religious'), ('S', 'Seeds'), ('T', 'Tools')], max_length=2),
        ),
    ]
