# Generated by Django 4.2.3 on 2023-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'Normal'), ('M', 'Medicinal'), ('R', 'Religious'), ('S', 'Seeds'), ('T', 'Tools')], max_length=2),
        ),
    ]
